# Generated by Django 3.2.4 on 2021-06-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotelab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotelab',
            name='Channel1',
            field=models.CharField(default='SOME STRING', max_length=1, verbose_name='Channel1'),
        ),
        migrations.AddField(
            model_name='remotelab',
            name='Channel2',
            field=models.CharField(default='SOME STRING', max_length=2, verbose_name='Channel2'),
        ),
        migrations.AddField(
            model_name='remotelab',
            name='PotValue',
            field=models.IntegerField(default=0, verbose_name='PotValue'),
        ),
        migrations.AddField(
            model_name='remotelab',
            name='acInput1',
            field=models.FloatField(default=0, verbose_name='acInput1'),
        ),
        migrations.AddField(
            model_name='remotelab',
            name='dcInput1',
            field=models.IntegerField(default=0, verbose_name='dcInput1'),
        ),
        migrations.AddField(
            model_name='remotelab',
            name='dcInput2',
            field=models.IntegerField(default=0, verbose_name='dcInput2'),
        ),
        migrations.AddField(
            model_name='remotelab',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
