# Generated by Django 3.2.4 on 2021-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotelab', '0003_auto_20210608_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelab',
            name='Channel1',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Channel1'),
        ),
        migrations.AlterField(
            model_name='remotelab',
            name='Channel2',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Channel2'),
        ),
        migrations.AlterField(
            model_name='remotelab',
            name='PotValue',
            field=models.IntegerField(blank=True, default=0, verbose_name='PotValue'),
        ),
        migrations.AlterField(
            model_name='remotelab',
            name='acInput1',
            field=models.FloatField(blank=True, default=0, verbose_name='acInput1'),
        ),
        migrations.AlterField(
            model_name='remotelab',
            name='dcInput1',
            field=models.IntegerField(blank=True, default=0, verbose_name='dcInput1'),
        ),
        migrations.AlterField(
            model_name='remotelab',
            name='dcInput2',
            field=models.IntegerField(blank=True, default=0, verbose_name='dcInput2'),
        ),
        migrations.AlterField(
            model_name='remotelab',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add Image to Experiment'),
        ),
    ]
